In [16]:
import numpy as np
import cv2

In [17]:
def av_pix(img,circles,size):
    av_value = []
    for m in circles[0,:]:
        col = np.mean(img[m[1]-size:m[1]+size,m[0]-size:m[0]+size])
#         print(img[m[1]-size:m[1]+size,m[0]-size:m[0]+size])
        av_value.append(col)
    return av_value

In [18]:
def get_radius(circles):
    radius = []
    for r in circles[0,:]:
        radius.append(r[2])
    return radius

In [19]:
img = cv2.imread('capstone_coins.png', cv2.IMREAD_GRAYSCALE)
original_image = cv2.imread('capstone_coins.png', 1)
img = cv2.GaussianBlur(img,(5,5),0)

In [20]:
circles = cv2.HoughCircles(img,cv2.HOUGH_GRADIENT, 0.9, 120, param1=50,param2=27,minRadius=60,maxRadius=120)

In [22]:
print(circles)

[[[1357.5  253.5  112.8]
  [1629.5  281.5   88.8]
  [ 994.5  132.5  108. ]
  [1203.5  742.5  103.1]
  [ 976.5  638.5   99.5]
  [1696.5  500.5  119.4]
  [1256.5  467.5  106.1]
  [1433.5  642.5  119.4]]]


In [23]:
circles = np.uint16(np.around(circles))
count = 1
for i in circles[0,:]:
#     draw the outer circle
    cv2.circle(original_image,(i[0],i[1]),i[2], (0,255,0), 2)
#     draw the center of the circle
    cv2.circle(original_image,(i[0],i[1]),2,(0,0,255),3)
#     cv2.putText(original_image, str(count),(i[0],i[1]), cv2.FONT_HERSHEY_SIMPLEX,2,(0,0,0),2)
    count += 1

In [10]:
# cv2.imshow('Detected Coins', original_image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [24]:
radius = get_radius(circles)
print(radius)

[113, 89, 108, 103, 100, 119, 106, 119]


In [25]:
bright_values = av_pix(img,circles,20)
print(bright_values)

[185.45375, 180.9975, 100.78625, 75.79375, 75.544375, 95.278125, 126.86625, 87.255]


In [26]:
res = []
for i,j in zip(bright_values, radius):
    if i > 150 and j > 110:
        res.append(10)
    elif i >150 and j <=110:
        res.append(5)
    elif i < 150 and j > 110:
        res.append(2)
    elif i < 150 and j < 110:
        res.append(1)
print(res)

[10, 5, 1, 1, 1, 2, 1, 2]


In [31]:
count2 = 0
for i in circles[0,:]:
    cv2.putText(original_image, str(res[count2])+'p',(i[0],i[1]), cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,0), 2)
    count2 += 1
cv2.putText(original_image, 'ESTIMATED TOTAL VALUE:' + str(sum(res)) + 'p', (200,100), cv2.FONT_HERSHEY_SIMPLEX, 1.3, 255)

array([[[160, 149, 148],
        [164, 153, 151],
        [157, 146, 145],
        ...,
        [159, 153, 156],
        [157, 152, 155],
        [155, 150, 153]],

       [[153, 142, 141],
        [157, 146, 145],
        [166, 155, 154],
        ...,
        [159, 153, 156],
        [157, 152, 155],
        [155, 150, 153]],

       [[168, 158, 154],
        [166, 156, 152],
        [164, 153, 151],
        ...,
        [160, 155, 156],
        [159, 154, 154],
        [152, 147, 147]],

       ...,

       [[158, 149, 139],
        [165, 156, 145],
        [170, 160, 154],
        ...,
        [172, 166, 164],
        [174, 167, 167],
        [176, 169, 170]],

       [[174, 164, 160],
        [168, 158, 154],
        [172, 159, 156],
        ...,
        [171, 167, 167],
        [173, 168, 168],
        [177, 173, 173]],

       [[174, 164, 160],
        [172, 161, 158],
        [169, 157, 153],
        ...,
        [173, 168, 168],
        [177, 173, 173],
        [171, 167, 167]]

In [32]:
cv2.imshow('Detected Coins', original_image)
cv2.waitKey(0)
cv2.destroyAllWindows()